아이디어 관리 사이트/posts/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "posts"

urlpatterns = [
    path('',views.home,name='home'),
    path('create/', views.create, name='create'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

    path('devtools/',views.devtool,name='devtoolshome'),
    path('devtools/create/', views.devtoolcreate, name='devtoolscreate'),
    path('devtools/detail/<int:id>/', views.devtooldetail, name='devtoolsdetail'),
    path('devtools/update/<int:id>/', views.devtoolupdate, name='devtoolsupdate'),
    path('devtools/delete/<int:id>/', views.devtooldelete, name='devtoolsdelete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

아이디어 관리 사이트/posts/models.py
from datetime import date
from operator import mod
from turtle import title
from django.db import models

# Create your models here.

class Devtool(models.Model):
    name = models.CharField(max_length=30,verbose_name='devtool name')
    kind = models.CharField(max_length=30,verbose_name='종류')
    content = models.TextField(verbose_name='content')

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='title')
    image = models.ImageField(blank = True, upload_to='posts/%Y%M%D',verbose_name='image')
    content = models.TextField(verbose_name='content')
    interest = models.IntegerField(default=0,verbose_name='관심도')
    devtool = models.ForeignKey(Devtool,on_delete = models.PROTECT,related_name='post_devtool')
    ideastar = models.BooleanField(default=False,verbose_name='아이디어스타')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='created at')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='updated at')

아이디어 관리 사이트/posts/views.py
from email.mime import image
import json
from unicodedata import name
from django.shortcuts import render, redirect
from .models import Devtool, Post

from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def home(request):
    if(request.method == 'POST'):
        req = json.loads(request.body)
        try:
            ineter = req['interest']
            Post.objects.filter(id = req['id']).update(interest = ineter)
        except KeyError:
            pass
        ideastar = Post.objects.get(id = req['star']).ideastar
        Post.objects.filter(id = req['star']).update(ideastar = not ideastar)

            
    query = request.GET.get('query',None)
    if query:
        #제목으로 검색
        posts = Post.objects.order_by(query)
    else:
        posts = Post.objects.all()

    context = {
        'posts': posts
    }
    return render(request, 'posts/home.html',context)

def create(request):
    if request.method == 'POST':
        title = request.POST['title']
        image = request.FILES['image']
        content = request.POST['content']
        interest = request.POST['interest']
        devtool = Devtool.objects.get(id = request.POST['devtool'])
        
        Post.objects.create(title = title,image = image, content= content, interest=interest, devtool= devtool)

        return redirect('/detail/'+str(Post.objects.latest('id').id))

    devtools = Devtool.objects.all()

    context = {
        'devtools': devtools
    }
    return render(request, 'posts/create.html',context)


def detail(request, id):
    post = Post.objects.get(id=id)
    context = {
        'post': post
    }
    return render(request, 'posts/detail.html', context)

def update(request, id):
    if request.method == 'POST':
        post = Post.objects.get(id=id)
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.interest = request.POST['interest']
        post.devtool = Devtool.objects.get(id = request.POST['devtool'])
        if request.FILES['image']:
            post.image = request.FILES['image']
        else:
            post.image = post.image

        post.save()
        return redirect('/detail/'+str(post.id))
    post = Post.objects.get(id=id)
    devtools = Devtool.objects.all()
    context = {
        'post': post,
        'devtools': devtools
    }
    return render(request, 'posts/update.html', context)

def delete(request, id):
    if request.method == 'POST':
        Post.objects.filter(id = id).delete()
        return redirect('/')
    post = Post.objects.get(id=id)
    context = {
        'post': post
    }
    return render(request, 'posts/delete.html', context)


def devtool(request):
    query = request.GET.get('query',None)
    if query:
        #제목으로 검색
        devtools = Devtool.objects.order_by(query)
    else:
        devtools = Devtool.objects.all()
    context = {
        'devtools': devtools
    }
    return render(request, 'devtools/home.html',context)

def devtoolcreate(request):
    if request.method == 'POST':
        name = request.POST['name']
        kind = request.POST['kind']
        content = request.POST['content']
        Devtool.objects.create(name = name, kind = kind, content = content)
        return redirect('/devtools/detail/'+str(Devtool.objects.latest('id').id))
    context = {}
    return render(request, 'devtools/create.html',context)

def devtooldetail(request, id):
    devtool = Devtool.objects.get(id=id)
    posts = Post.objects.filter(devtool = devtool)
    context = {
        'devtool': devtool,
        'posts': posts
    }
    return render(request, 'devtools/detail.html', context)

def devtoolupdate(request, id):
    if request.method == 'POST':
        devtool = Devtool.objects.get(id=id)
        devtool.name = request.POST['name']
        devtool.kind = request.POST['kind']
        devtool.content = request.POST['content']
        devtool.save()
        return redirect('/devtools/detail/'+str(devtool.id))
    devtool = Devtool.objects.get(id=id)
    context = {
        'devtool': devtool
    }
    return render(request, 'devtools/update.html', context)

def devtooldelete(request, id):
    if request.method == 'POST':
        Devtool.objects.filter(id = id).delete()
        return redirect('/devtools/')
    devtool = Devtool.objects.get(id=id)
    context = {
        'devtool': devtool
    }
    return render(request, 'devtools/delete.html', context)

아이디어 관리 사이트/posts/templates/devtools/create.html
{% extends 'posts/base.html' %}{% block content %}

<form action="{% url 'posts:devtoolscreate' %}" method="post">
  {% csrf_token %}
  <h2>
    <input type="text" name="name" placeholder="이름" />
  </h2>
  <p>
    <input type="text" name="kind" placeholder="종류" />
  </p>
  <textarea name="content" id="" cols="30" rows="10"></textarea>

  <div>
    <input type="submit" value="제출" />
  </div>
</form>
<a href="/devtools">Home</a>
{% endblock %}

아이디어 관리 사이트/posts/templates/devtools/detail.html
{% extends 'posts/base.html' %} {% block content %}

<article>
  <div>
    <h2>
      이름 :
      <a href="{% url 'posts:devtoolsdetail' devtool.id %}"
        >{{ devtool.name }}</a
      >
    </h2>
    <div>종류 : {{devtool.kind}}</div>
    <div>내용: {{devtool.content}}</div>

    <div>
      <p>만들 수 있는 게시글 목록</p>
      {% for post in posts %}
      <a href="{% url 'posts:detail' post.id %}">{{post.title}}</a>
      {% endfor %}
    </div>
  </div>
</article>

<div>
  업데이트 : <a href="{% url 'posts:devtoolsupdate' devtool.id %} ">update</a>
</div>
<a href="/devtools/">목록</a>
<form action="{% url 'posts:devtoolsdelete' devtool.id %}" method="post">
  {% csrf_token %}
  <button>삭제</button>
</form>

{% endblock %}

아이디어 관리 사이트/posts/templates/devtools/home.html
{% extends 'posts/base.html' %}{% block content %} {% for tool in devtools %}
<article>
  <div>
    <a href="{% url 'posts:devtoolsdetail' tool.id %}">{{tool.name}}</a>
    <p>{{tool.kind}}</p>
    <p>{{tool.content}}</p>
  </div>
</article>
{% endfor %} {% endblock %}

아이디어 관리 사이트/posts/templates/devtools/update.html
{% extends 'posts/base.html' %}{% block content %}
<form
  action="{% url 'devtools:update' devtool.id %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <h2>
    <input
      type="text"
      name="name"
      placeholder="이름"
      value="{{devtool.name}}"
    />
  </h2>
  <p>
    <input
      type="number"
      name="kind"
      placeholder="종류"
      value="{{devtool.kind}}"
    />
  </p>
  <textarea name="content" id="" cols="30" rows="10">
{{devtool.content}}</textarea
  >

  <div>
    <input type="submit" value="제출" />
  </div>
</form>
<a href="/devtools/">Home</a>{% endblock %}

아이디어 관리 사이트/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/ideabase.css' %}" />
    {% block extrahead %} {% endblock %}
    <title>아이디어 리스트</title>
  </head>
  <body>
    <header>
      <div><a href="/">my idea list</a></div>
      <div>
        <a href="/create">아이디어 등록</a>
        <a href="/">아이디어 관리</a>
        <a href="/devtools/create">개발툴 등록</a>
        <a href="/devtools">개발툴 관리</a>
      </div>
    </header>
    <div style="height: 1px; background-color: black"></div>
    <div id="main-box">{% block content %} {% endblock %}</div>
  </body>
</html>

아이디어 관리 사이트/posts/templates/posts/create.html
{% extends 'posts/base.html' %}{% block content %}
<form
  action="{% url 'posts:create' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <h2>
    <input type="text" name="title" placeholder="제목" />
  </h2>
  <p>
    <input type="file" name="image" />
  </p>
  <p>
    <select name="devtool">
      {% for tool in devtools %}
      <option value="{{tool.id}}">{{tool.name}}</option>
      {% endfor %}
    </select>
    <input type="number" name="interest" placeholder="관심도" />
  </p>
  <textarea name="content" id="" cols="30" rows="10"></textarea>

  <div>
    <input type="submit" value="제출" />
  </div>
</form>
<a href="/">Home</a>
{% endblock %}

아이디어 관리 사이트/posts/templates/posts/detail.html
{% extends 'posts/base.html' %}

<head>
  {% load static %} {% block extrahead %}
  <link rel="stylesheet" href="{% static 'css/ideahome.css' %}" />
  <script
    src="https://kit.fontawesome.com/c1be11131c.js"
    crossorigin="anonymous"
  ></script>
  {% endblock %}
</head>
{% block content %}

<article>
  <div>
    <img src="{{ post.image.url }}" />
  </div>
  <div>
    {% if post.ideastar == False %}
    <i class="fa-regular fa-star" style="color: #ffc107"></i>
    {% else %}
    <i class="fa-solid fa-star" style="color: #ffc107"></i>
    {% endif %}
    <h2>제목 : {{ post.title }}</h2>
    <div>내용 : {{post.content}}</div>
    <div>관심도 : {{post.interest}}</div>
    <div>
      개발 도구:
      <a href="{% url 'posts:devtoolsdetail' post.devtool.id %}"
        >{{post.devtool.name}}</a
      >
    </div>
  </div>
</article>

<div>업데이트 : <a href="{% url 'posts:update' post.id %} ">update</a></div>
<a href="/">목록</a>
<form action="{% url 'posts:delete' post.id %}" method="post">
  {% csrf_token %}
  <button>삭제</button>
</form>

{% endblock %}

아이디어 관리 사이트/posts/templates/posts/home.html
{% extends 'posts/base.html' %}
<head>
  {% load static %} {% block extrahead %}
  <link rel="stylesheet" href="{% static 'css/ideahome.css' %}" />
  <script
    src="https://kit.fontawesome.com/c1be11131c.js"
    crossorigin="anonymous"
  ></script>
  {% endblock %}
</head>

{% block content %}

<div style="display: flex; align-items: center">
  <p style="margin-right: 3rem; margin-left: 4rem">정렬</p>
  <form action="{% url 'posts:home'%}" method="get">
    <select name="query">
      <option value="title">이름순</option>
      <option value="interest">관심도</option>
      <option value="ideastar">찜하기</option>
      <option value="created_at">등록순</option>
      <option value="updated_at">최신순</option>
    </select>
    <input type="submit" value="검색" />
  </form>
</div>

{% for post in posts %}
<article>
  {% if post.image %}
  <div id="img-box">
    <button id="{{post.id}}" onclick="idea_like({{post.id}})">
      {% if post.ideastar == False %}
      <i class="fa-regular fa-star" style="color: #ffc107"></i>
      {% else %}
      <i class="fa-solid fa-star" style="color: #ffc107"></i>
      {% endif %}
    </button>
    <img src="{{ post.image.url }}" />
  </div>
  {% endif %}

  <div>
    <a href="{% url 'posts:detail' post.id %}">{{post.title}}</a>
    <p>
      <a href="{% url 'posts:devtoolsdetail' post.devtool.id %}"
        >{{post.devtool.name}}</a
      >
    </p>
    <div>
      <span onclick="plus({{post.id}})">+</span>
      <p id="{{post.id}}">{{post.interest}}</p>
      <span onclick="minus({{post.id}})">-</span>
    </div>
  </div>
</article>
{% endfor %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'javascript/interest.js' %}"></script>
{% endblock %}

아이디어 관리 사이트/posts/templates/posts/update.html
{% extends 'posts/base.html' %}{% block content %}
<form
  action="{% url 'posts:update' post.id %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <h2>
    <input type="text" name="title" placeholder="제목" value="{{post.title}}" />
  </h2>
  <p>
    <p>이미지 : {{ post.image.url }}</p>
    <input type="file" name="image" value="{{ post.image.url }}" />
  </p>
  <p>
    <select name="devtool">
      {% for tool in devtools %}
      <option value="{{tool.id}}">{{tool.name}}</option>
      {% endfor %}
    </select>
    <input
      type="number"
      name="interest"
      placeholder="관심도"
      value="{{post.interest}}"
    />
  </p>
  <textarea name="content" id="" cols="30" rows="10">{{post.content}}</textarea>

  <div>
    <input type="submit" value="제출" />
  </div>
</form>
<a href="/">Home</a>{% endblock %}