myMovieReviews/reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

app_name = "reviews"

myMovieReviews/reviews/models.py
from turtle import title
from django.db import models

# Create your models here.
class Review(models.Model):
    genrecategory=(('Action','Action'),('Adventure','Adventure'),('Animation','Animation'),('Comedy','Comedy'),('Crime','Crime'),('Documentary','Documentary'),('Drama','Drama'),('Family','Family'),('Fantasy','Fantasy'),('History','History'),('Horror','Horror'),('Music','Music'),('Mystery','Mystery'),('Romance','Romance'),('Science Fiction','Science Fiction'),('TV Movie','TV Movie'),('Thriller','Thriller'),('War','War'),('Western','Western'))
    title = models.CharField(max_length=100, verbose_name="Title")
    openyear = models.IntegerField(verbose_name="Open Year")
    genre= models.CharField(max_length=100, choices=genrecategory)
    starpoint = models.IntegerField(verbose_name="Star Point")
    director = models.CharField(max_length=100, verbose_name="Director")
    actor = models.CharField(max_length=100, verbose_name="Actor")
    runningtime = models.IntegerField(verbose_name="Running Time")
    review = models.TextField(verbose_name="Review")

myMovieReviews/reviews/views.py
from multiprocessing import context
from turtle import title
from unicodedata import category
from django.shortcuts import render, redirect
from .models import Review

# Create your views here.

def home(request):
    query = request.GET.get('query',None)
    if query:
        #제목으로 검색
        reviews = Review.objects.order_by(query)
    else:
        reviews = Review.objects.all()
    context = {
        'reviews': reviews
    }
    return render(request, 'reviews/home.html',context)

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        openyear = request.POST.get('openyear')
        genre = request.POST.get('genre')
        starpoint = request.POST.get('starpoint')
        director = request.POST.get('director')
        actor = request.POST.get('actor')
        runningtime = request.POST.get('runningtime')
        review = request.POST.get('review')
        Review.objects.create(title=title, openyear=openyear, genre=genre, starpoint=starpoint, director=director, actor=actor, runningtime=runningtime, review=review)

        return redirect('/')

    context = {
        'category': Review.genrecategory
    }
    return render(request, 'reviews/create.html',context)


def detail(request, id):
    #Post라는 class의 객체들 중에 id를 가진 객체를 찾아옴
    review = Review.objects.get(id=id)
    context = {
        'review': review
    }
    return render(request, template_name='reviews/detail.html', context = context)


def update(request, id):
    if request.method == 'POST':
        title = request.POST['title']
        openyear = request.POST['openyear']
        genre = request.POST['genre']
        starpoint = request.POST['starpoint']
        director = request.POST['director']
        actor = request.POST['actor']
        runningtime = request.POST['runningtime']
        review = request.POST['review']


        Review.objects.filter(id = id).update(title=title, openyear=openyear, genre=genre, starpoint=starpoint, director=director, actor=actor, runningtime=runningtime, review=review)
        return redirect('/detail/'+str(id))

    review = Review.objects.get(id=id)
    context = {
        'review': review
    }
    return render(request, template_name='reviews/update.html', context = context)

def delete(request, id):
    if request.method == 'POST':
        Review.objects.filter(id = id).delete()
        return redirect('/')

myMovieReviews/reviews/templates/reviews/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/reviews.css' %}" />
    <title>홈 화면</title>
  </head>
  <body>
    <header>
      <div>my Movie review</div>
      <div>
        <a href="/create">리뷰 작성</a>
      </div>
    </header>
    <div style="height: 1px; background-color: black"></div>
    {% block content %} {% endblock %}
  </body>
</html>

myMovieReviews/reviews/templates/reviews/create.html
{% extends 'reviews/base.html' %}{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <h2>
    <input type="text" name="title" placeholder="제목" />
  </h2>
  <p>
    <input type="text" name="openyear" placeholder="개봉 년도" />
    <select name="genre">
      {% for key, value in category %}
      <option value="{{key}}">{{value}}</option>
      {% endfor %}
    </select>
    <input type="number" name="starpoint" placeholder="별점" />
    <input type="text" name="director" placeholder="감독" />
    <input type="text" name="actor" placeholder="주연 배우" />
    <input type="number" name="runningtime" placeholder="러닝타임" />
  </p>
  <textarea name="review" id="" cols="30" rows="10"></textarea>

  <div>
    <input type="submit" value="제출" />
  </div>
</form>
<a href="/">Home</a>
{% endblock %}

myMovieReviews/reviews/templates/reviews/detail.html
{% extends 'reviews/base.html' %}{% block content %}
<article>
  <h2>제목 : {{ review.title }}</h2>
  <p>{{review.openyear}}</p>
  <p>장르: {{review.genre}}</p>
  <p>감독: {{ review.director }}</p>
  <p>주연배우: {{review.actor}}</p>
  <p>별점: {{review.starpoint}}</p>
  <p>러닝타임: {{review.runningtime}}</p>

  <div>{{review.review}}</div>
</article>

<div style="display: flex; margin: 4rem; align-items: center">
  <div style="margin-right: 3rem">
    수정 : <a href="{% url 'reviews:update' review.id %} ">수정</a>
  </div>
  <form action="{% url 'reviews:delete' review.id %} " method="post">
    {% csrf_token %}
    <button>삭제</button>
  </form>
</div>

<div><a href="/">my Movie reviews</a></div>
{% endblock %}

myMovieReviews/reviews/templates/reviews/home.html
{% extends 'reviews/base.html' %}{% block content %}
<div style="display: flex; align-items: center">
  <p style="margin-right: 3rem; margin-left: 4rem">정렬</p>
  <form action="{% url 'reviews:home'%}" method="get">
    <select name="query">
      <option value="">등록순</option>
      <option value="title">제목</option>
      <option value="openyear">개봉 년도</option>
      <option value="genre">장르</option>
      <option value="starpoint">별점</option>
      <option value="runningtime">러닝타임</option>
    </select>
    <input type="submit" value="검색" />
  </form>
</div>
{% for review in reviews %}
<article>
  <h1>
    <a href="{% url 'reviews:detail' review.id %}">{{review.title}}</a>
  </h1>
  <p>개봉 년도: {{review.openyear}}</p>
  <p>장르: {{review.genre}}</p>
  <p>별점: {{review.starpoint}}</p>
</article>
{% endfor %} {% endblock %}

myMovieReviews/reviews/templates/reviews/update.html
{% extends 'reviews/base.html' %}{% block content %}
<form action="/update/{{review.id}}/" method="post">
  {% csrf_token %}
  <h2>
    <input
      type="text"
      name="title"
      placeholder="제목"
      value="{{review.title}}"
    />
  </h2>
  <p>
    <input
      type="text"
      name="openyear"
      placeholder="개봉 년도"
      value="{{review.title}}"
    />
    <select name="genre">
      {% for key, value in review.genrecategory %} {% if review.genre == key %}
      <option value="{{key}}" selected>{{value}}</option>
      {% else %}보
      <option value="{{key}}">{{value}}</option>
      {% endif %} {% endfor %}
    </select>
    <input
      type="number"
      name="starpoint"
      placeholder="별점"
      value="{{review.starpoint}}"
    />
    <input
      type="text"
      name="director"
      placeholder="감독"
      value="{{review.director}}"
    />
    <input
      type="text"
      name="actor"
      placeholder="주연 배우"
      value="{{review.actor}}"
    />
    <input
      type="number"
      name="runningtime"
      placeholder="러닝타임"
      value="{{review.runningtime}}"
    />
  </p>
  <textarea name="review" id="" cols="30" rows="10">{{review.review}}</textarea>

  <div>
    <input type="submit" value="저장" />
  </div>
</form>
<a href="/">Home</a>
{% endblock %}